from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import os, requests, json

app = FastAPI(title="SIEM Playground Collector")

# Enable CORS for React dev server
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class Event(BaseModel):
    timestamp: str
    source: str
    event_type: str
    payload: dict


QUEUE_FILE = "/tmp/siem_events.jsonl"
ALERTS_FILE = "/tmp/siem_alerts.jsonl"


@app.post("/ingest")
async def ingest(e: Event):
    line = e.json()
    with open(QUEUE_FILE, "a") as f:
        f.write(line + "\n")
    return {"status": "queued"}


@app.get("/api/alerts")
async def get_alerts():
    """Read alerts generated by the pipeline"""
    if not os.path.exists(ALERTS_FILE):
        return []

    with open(ALERTS_FILE, "r") as f:
        alerts = [json.loads(line) for line in f if line.strip()]

    return alerts


@app.get("/health")
def health():
    return {"status": "ok"}
